name: Build and Deploy to EC2 with Matrix Testing

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]          # Test on multiple Node.js versions
        os: [ubuntu-latest, windows-latest]  # Test on multiple OSs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Retrieve PAT token from secret
        run: sed -i 's/TOKEN/${{ secrets.TOKEN }}/g' .env
        
      - name: Set execute permissions on Jest
        run: chmod +x ./node_modules/.bin/jest
        
      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Archive dist folder
        run: tar -czf dist-${{ matrix.os }}-${{ matrix.node-version }}.tar.gz dist

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy dist folder to EC2
        run: |
          scp -o StrictHostKeyChecking=no dist-ubuntu-latest-22.tar.gz ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/dist.tar.gz

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Stop the existing app
            pkill -f "npm start" || true
            

            # Unpack the dist folder
            cd /home/ec2-user
            tar -xzf dist.tar.gz -C /home/ec2-user/

            # Install dependencies if not already done
            cd /home/ec2-user/dist
            npm install --only=prod

            # Start the app
            nohup npm start > app.log 2>&1 &
          EOF

